### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [romulobrasil/PureMask.js#7]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by romulobrasil** [comment]
Quais seriam as suas ideias, amigo?

**Comment by ghost** [comment]
Oi romulobrasil.

> Quais seriam as suas ideias, amigo?

Vi sua mensagem hoje, perdão pela demora em responder. Vou listar cada uma dessas ideias e espero que me passe um feedback sobre cada uma de forma positiva ou negativa. 

1. gostaria de um site personalizado apenas para a biblioteca no GitHub Pages como: `https://puremask.github.io/` - acho mais interessante ter um site personalizado do que `https://apps.romulobrasil.com/puremask`. Entendo que é o dono e proprietário ou principal colaborador, mantenedor da biblioteca - mas geralmente alguns optam por um site personalizado para a biblioteca. Nesse sentido, gostaria de saber se isso é interessante, bom, ruim ou necessário - ou se é relevante para você caso tenha pensando ou não nesta ideia.

*ideia 1*
![image](https://user-images.githubusercontent.com/111701513/213486693-8f565b39-571c-43dc-a285-9e8d0c2bac96.png)

2. penso em ter uma mesma base de código para diversos frameworks em js como react, vuejs com base na biblioteca puremask.js - a minha ideia aqui é oferecer maior extensibilidade da biblioteca para que outros programadores possam utilizar.

3. discussões sobre novas implementações. Existe uma opção chamada GitHub Discussions, é possível discutir ideias, conceitos e soluções antes de criar issues. Penso em inicialmente, elaborar algumas ideias e conceitos antes de issues no GitHub Discussions para puremask.js

*ideia 3* 
![image](https://user-images.githubusercontent.com/111701513/213367638-1c2127f6-2b07-42a2-a199-b2ce72f9d7c9.png)

4. Adicionar licença no projeto. não encontrei essa informação, segue uma ideia:

*ideia 4*
![image](https://user-images.githubusercontent.com/111701513/213373719-05ac7c9f-492c-4299-a88c-c3ab6abd1b05.png)

5. Por qual razão não existe o link no repositório da biblioteca js?
![image](https://user-images.githubusercontent.com/111701513/213368091-2909bd31-7dfc-4c43-9767-afdeb25adf5d.png)

6. A logo do projeto - pensei em algo mais diferente, único, interessante e que demonstre ou seja próxima ao valor, escopo ou propósito da biblioteca em js. Pensei em algo assim:

*ideia 6*
![image](https://user-images.githubusercontent.com/111701513/213367921-7edfe288-53f1-4400-b48e-0a7a4a6a5ab3.png)

*Por qual razão esse símbolo pode representar esse projeto?*
- O símbolo é da máscara de teatro. Pensei inicialmente em utilizar esse símbolo para representar o conceito de "papéis, funções, cargos que desempenhamos como programadores" que podem ser bons ou ruins dependendo de cada pessoa. 
- Além dessa razão, como gosto bastante de teatro e pensei em utilizar esse símbolo justamente por lembrar disso, é meio que um trocadilho com cinco sentidos. Deixe-me explicar:
   - O primeiro sentido seria deste símbolo representar a experiência na área de programação que pode ser boa ou ruim a depender de cada pessoa. Ao mesmo tempo que, esse símbolo representa meu gosto por teatro em um segundo sentido também.
   - Assim como, em um terceiro sentido também, representa uma biblioteca que utilizo com bastante frequência para filtrar o que o usuário digita em campos e que possui várias funcionalidades, daí o conceito de máscara com o símbolo da máscara de teatro. 
   - Ao mesmo tempo que - por sua vez, um quarto sentido, esse símbolo está associado ao carnaval que é algo histórico no Brasil.
   - Um quinto e último sentido, seria que representa a dualidade de espírito, o momento em que estamos felizes e tristes na vida.
- O último motivo é que a licença do símbolo é gratuita com atribuição (ps: não fui eu quem desenvolvi o símbolo, mas pensei em utilizar aqui): `https://flaticon.com/br/icone-gratis/mascara-de-carnaval_1172029?related_id=1172080&origin=search`*`

*tudo isso que escrevi são algumas sugestões ou apenas sugestões de melhoria. O que pensa sobre essas 6 ideias? são boas ou ruins?*

**Comment by ghost** [comment]
Achei boas as ideias. uma ideia, seria ativar uma opção de doação caso alguém queira financiar o projeto de código aberto.
